In [5]:
import numpy as np

In [86]:
X = np.array([0.1,0.2])
W = np.array([1,2,3,4]).reshape((2,2))
B = np.array([1,2])
E = 0.9

In [87]:
Y = np.dot(X, W) + B
print(Y)

Y_exp = np.array([2, 4])

[1.7 3. ]


In [88]:
# Generate shapes that allow you to produce a matrix
X_reshaped = X.reshape(2,1)
print(X_reshaped)

diff_exp = Y - Y_exp
diff_exp = diff_exp.reshape(1,2)
print(diff_exp)

[[0.1]
 [0.2]]
[[-0.3 -1. ]]


In [89]:
W

array([[1, 2],
       [3, 4]])

In [90]:
W_new = W + E * np.dot(X_reshaped, diff_exp)
W_new

array([[0.973, 1.91 ],
       [2.946, 3.82 ]])

In [91]:
Y = np.dot(X, W_new) + B
print(Y)


[1.6865 2.955 ]
